name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: BUild Step
        run: scho "A demo build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test phase
        run: echo "Running test phase"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to App
        run: scho "Deploying the app"
